import "../styles/globals.css";
import Header from "./Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 transition-all">
        <Header />
        <div className="max-w-6xl mx-auto px-5">{children}</div>
      </body>
    </html>
  );
}
